declare namespace Dyn365WebApi {
  interface Opportunity_Base extends WebEntity {
    actualclosedate?: Date | null;
    actualvalue?: number | null;
    actualvalue_base?: number | null;
    budgetamount?: number | null;
    budgetamount_base?: number | null;
    budgetstatus?: budgetstatus | null;
    captureproposalfeedback?: boolean | null;
    closeprobability?: number | null;
    completefinalproposal?: boolean | null;
    completeinternalreview?: boolean | null;
    confirminterest?: boolean | null;
    createdon?: Date | null;
    currentsituation?: string | null;
    customerneed?: string | null;
    customerpainpoints?: string | null;
    decisionmaker?: boolean | null;
    description?: string | null;
    developproposal?: boolean | null;
    discountamount?: number | null;
    discountamount_base?: number | null;
    discountpercentage?: number | null;
    emailaddress?: string | null;
    estimatedclosedate?: Date | null;
    estimatedvalue?: number | null;
    estimatedvalue_base?: number | null;
    evaluatefit?: boolean | null;
    exchangerate?: number | null;
    filedebrief?: boolean | null;
    finaldecisiondate?: Date | null;
    freightamount?: number | null;
    freightamount_base?: number | null;
    identifycompetitors?: boolean | null;
    identifycustomercontacts?: boolean | null;
    identifypursuitteam?: boolean | null;
    importsequencenumber?: number | null;
    initialcommunication?: initialcommunication | null;
    isprivate?: boolean | null;
    isrevenuesystemcalculated?: boolean | null;
    lastonholdtime?: Date | null;
    modifiedon?: Date | null;
    name?: string | null;
    need?: need | null;
    onholdtime?: number | null;
    opportunityid?: string | null;
    opportunityratingcode?: opportunity_opportunityratingcode | null;
    overriddencreatedon?: Date | null;
    participatesinworkflow?: boolean | null;
    presentfinalproposal?: boolean | null;
    presentproposal?: boolean | null;
    pricingerrorcode?: qooi_pricingerrorcode | null;
    prioritycode?: opportunity_prioritycode | null;
    processid?: string | null;
    proposedsolution?: string | null;
    purchaseprocess?: purchaseprocess | null;
    purchasetimeframe?: purchasetimeframe | null;
    pursuitdecision?: boolean | null;
    qualificationcomments?: string | null;
    quotecomments?: string | null;
    resolvefeedback?: boolean | null;
    salesstage?: opportunity_salesstage | null;
    salesstagecode?: opportunity_salesstagecode | null;
    schedulefollowup_prospect?: Date | null;
    schedulefollowup_qualify?: Date | null;
    scheduleproposalmeeting?: Date | null;
    sendthankyounote?: boolean | null;
    stageid?: string | null;
    statecode?: opportunity_statecode | null;
    statuscode?: opportunity_statuscode | null;
    stepid?: string | null;
    stepname?: string | null;
    timeline?: opportunity_timeline | null;
    timespentbymeonemailandmeetings?: string | null;
    timezoneruleversionnumber?: number | null;
    totalamount?: number | null;
    totalamount_base?: number | null;
    totalamountlessfreight?: number | null;
    totalamountlessfreight_base?: number | null;
    totaldiscountamount?: number | null;
    totaldiscountamount_base?: number | null;
    totallineitemamount?: number | null;
    totallineitemamount_base?: number | null;
    totallineitemdiscountamount?: number | null;
    totallineitemdiscountamount_base?: number | null;
    totaltax?: number | null;
    totaltax_base?: number | null;
    transactioncurrencyid_guid?: string | null;
    traversedpath?: string | null;
    utcconversiontimezonecode?: number | null;
    versionnumber?: number | null;
  }
  interface Opportunity_Relationships {
    customerid_account?: Account_Result | null;
    customerid_contact?: Contact_Result | null;
    opportunity_PostFollows?: PostFollow_Result[] | null;
    opportunity_activity_parties?: ActivityParty_Result[] | null;
    opportunity_connections1?: Connection_Result[] | null;
    opportunity_connections2?: Connection_Result[] | null;
  }
  interface Opportunity extends Opportunity_Base, Opportunity_Relationships {
    campaignid_bind$campaigns?: string | null;
    customerid_account_bind$accounts?: string | null;
    customerid_contact_bind$contacts?: string | null;
    originatingleadid_bind$leads?: string | null;
    ownerid_bind$owners?: string | null;
    parentaccountid_bind$accounts?: string | null;
    parentcontactid_bind$contacts?: string | null;
    pricelevelid_bind$pricelevels?: string | null;
    sla_opportunity_sla_bind$slas?: string | null;
    stageid_processstage_bind$processstages?: string | null;
    transactioncurrencyid_bind$transactioncurrencies?: string | null;
  }
  interface Opportunity_Create extends Opportunity {
  }
  interface Opportunity_Update extends Opportunity {
  }
  interface Opportunity_Select {
    accountid_guid: WebAttribute<Opportunity_Select, { accountid_guid: string | null }, { accountid_formatted?: string }>;
    actualclosedate: WebAttribute<Opportunity_Select, { actualclosedate: Date | null }, { actualclosedate_formatted?: string }>;
    actualvalue: WebAttribute<Opportunity_Select, { actualvalue: number | null; transactioncurrencyid_guid: string | null }, { actualvalue_formatted?: string; transactioncurrencyid_formatted?: string }>;
    actualvalue_base: WebAttribute<Opportunity_Select, { actualvalue_base: number | null; transactioncurrencyid_guid: string | null }, { actualvalue_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    budgetamount: WebAttribute<Opportunity_Select, { budgetamount: number | null; transactioncurrencyid_guid: string | null }, { budgetamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
    budgetamount_base: WebAttribute<Opportunity_Select, { budgetamount_base: number | null; transactioncurrencyid_guid: string | null }, { budgetamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    budgetstatus: WebAttribute<Opportunity_Select, { budgetstatus: budgetstatus | null }, { budgetstatus_formatted?: string }>;
    campaignid_guid: WebAttribute<Opportunity_Select, { campaignid_guid: string | null }, { campaignid_formatted?: string }>;
    captureproposalfeedback: WebAttribute<Opportunity_Select, { captureproposalfeedback: boolean | null }, {  }>;
    closeprobability: WebAttribute<Opportunity_Select, { closeprobability: number | null }, {  }>;
    completefinalproposal: WebAttribute<Opportunity_Select, { completefinalproposal: boolean | null }, {  }>;
    completeinternalreview: WebAttribute<Opportunity_Select, { completeinternalreview: boolean | null }, {  }>;
    confirminterest: WebAttribute<Opportunity_Select, { confirminterest: boolean | null }, {  }>;
    contactid_guid: WebAttribute<Opportunity_Select, { contactid_guid: string | null }, { contactid_formatted?: string }>;
    createdby_guid: WebAttribute<Opportunity_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
    createdon: WebAttribute<Opportunity_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
    createdonbehalfby_guid: WebAttribute<Opportunity_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
    currentsituation: WebAttribute<Opportunity_Select, { currentsituation: string | null }, {  }>;
    customerid_guid: WebAttribute<Opportunity_Select, { customerid_guid: string | null }, { customerid_formatted?: string }>;
    customerneed: WebAttribute<Opportunity_Select, { customerneed: string | null }, {  }>;
    customerpainpoints: WebAttribute<Opportunity_Select, { customerpainpoints: string | null }, {  }>;
    decisionmaker: WebAttribute<Opportunity_Select, { decisionmaker: boolean | null }, {  }>;
    description: WebAttribute<Opportunity_Select, { description: string | null }, {  }>;
    developproposal: WebAttribute<Opportunity_Select, { developproposal: boolean | null }, {  }>;
    discountamount: WebAttribute<Opportunity_Select, { discountamount: number | null; transactioncurrencyid_guid: string | null }, { discountamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
    discountamount_base: WebAttribute<Opportunity_Select, { discountamount_base: number | null; transactioncurrencyid_guid: string | null }, { discountamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    discountpercentage: WebAttribute<Opportunity_Select, { discountpercentage: number | null }, {  }>;
    emailaddress: WebAttribute<Opportunity_Select, { emailaddress: string | null }, {  }>;
    estimatedclosedate: WebAttribute<Opportunity_Select, { estimatedclosedate: Date | null }, { estimatedclosedate_formatted?: string }>;
    estimatedvalue: WebAttribute<Opportunity_Select, { estimatedvalue: number | null; transactioncurrencyid_guid: string | null }, { estimatedvalue_formatted?: string; transactioncurrencyid_formatted?: string }>;
    estimatedvalue_base: WebAttribute<Opportunity_Select, { estimatedvalue_base: number | null; transactioncurrencyid_guid: string | null }, { estimatedvalue_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    evaluatefit: WebAttribute<Opportunity_Select, { evaluatefit: boolean | null }, {  }>;
    exchangerate: WebAttribute<Opportunity_Select, { exchangerate: number | null }, {  }>;
    filedebrief: WebAttribute<Opportunity_Select, { filedebrief: boolean | null }, {  }>;
    finaldecisiondate: WebAttribute<Opportunity_Select, { finaldecisiondate: Date | null }, { finaldecisiondate_formatted?: string }>;
    freightamount: WebAttribute<Opportunity_Select, { freightamount: number | null; transactioncurrencyid_guid: string | null }, { freightamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
    freightamount_base: WebAttribute<Opportunity_Select, { freightamount_base: number | null; transactioncurrencyid_guid: string | null }, { freightamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    identifycompetitors: WebAttribute<Opportunity_Select, { identifycompetitors: boolean | null }, {  }>;
    identifycustomercontacts: WebAttribute<Opportunity_Select, { identifycustomercontacts: boolean | null }, {  }>;
    identifypursuitteam: WebAttribute<Opportunity_Select, { identifypursuitteam: boolean | null }, {  }>;
    importsequencenumber: WebAttribute<Opportunity_Select, { importsequencenumber: number | null }, {  }>;
    initialcommunication: WebAttribute<Opportunity_Select, { initialcommunication: initialcommunication | null }, { initialcommunication_formatted?: string }>;
    isprivate: WebAttribute<Opportunity_Select, { isprivate: boolean | null }, {  }>;
    isrevenuesystemcalculated: WebAttribute<Opportunity_Select, { isrevenuesystemcalculated: boolean | null }, {  }>;
    lastonholdtime: WebAttribute<Opportunity_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
    modifiedby_guid: WebAttribute<Opportunity_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
    modifiedon: WebAttribute<Opportunity_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
    modifiedonbehalfby_guid: WebAttribute<Opportunity_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
    name: WebAttribute<Opportunity_Select, { name: string | null }, {  }>;
    need: WebAttribute<Opportunity_Select, { need: need | null }, { need_formatted?: string }>;
    onholdtime: WebAttribute<Opportunity_Select, { onholdtime: number | null }, {  }>;
    opportunityid: WebAttribute<Opportunity_Select, { opportunityid: string | null }, {  }>;
    opportunityratingcode: WebAttribute<Opportunity_Select, { opportunityratingcode: opportunity_opportunityratingcode | null }, { opportunityratingcode_formatted?: string }>;
    originatingleadid_guid: WebAttribute<Opportunity_Select, { originatingleadid_guid: string | null }, { originatingleadid_formatted?: string }>;
    overriddencreatedon: WebAttribute<Opportunity_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
    ownerid_guid: WebAttribute<Opportunity_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
    owningbusinessunit_guid: WebAttribute<Opportunity_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
    owningteam_guid: WebAttribute<Opportunity_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
    owninguser_guid: WebAttribute<Opportunity_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
    parentaccountid_guid: WebAttribute<Opportunity_Select, { parentaccountid_guid: string | null }, { parentaccountid_formatted?: string }>;
    parentcontactid_guid: WebAttribute<Opportunity_Select, { parentcontactid_guid: string | null }, { parentcontactid_formatted?: string }>;
    participatesinworkflow: WebAttribute<Opportunity_Select, { participatesinworkflow: boolean | null }, {  }>;
    presentfinalproposal: WebAttribute<Opportunity_Select, { presentfinalproposal: boolean | null }, {  }>;
    presentproposal: WebAttribute<Opportunity_Select, { presentproposal: boolean | null }, {  }>;
    pricelevelid_guid: WebAttribute<Opportunity_Select, { pricelevelid_guid: string | null }, { pricelevelid_formatted?: string }>;
    pricingerrorcode: WebAttribute<Opportunity_Select, { pricingerrorcode: qooi_pricingerrorcode | null }, { pricingerrorcode_formatted?: string }>;
    prioritycode: WebAttribute<Opportunity_Select, { prioritycode: opportunity_prioritycode | null }, { prioritycode_formatted?: string }>;
    processid: WebAttribute<Opportunity_Select, { processid: string | null }, {  }>;
    proposedsolution: WebAttribute<Opportunity_Select, { proposedsolution: string | null }, {  }>;
    purchaseprocess: WebAttribute<Opportunity_Select, { purchaseprocess: purchaseprocess | null }, { purchaseprocess_formatted?: string }>;
    purchasetimeframe: WebAttribute<Opportunity_Select, { purchasetimeframe: purchasetimeframe | null }, { purchasetimeframe_formatted?: string }>;
    pursuitdecision: WebAttribute<Opportunity_Select, { pursuitdecision: boolean | null }, {  }>;
    qualificationcomments: WebAttribute<Opportunity_Select, { qualificationcomments: string | null }, {  }>;
    quotecomments: WebAttribute<Opportunity_Select, { quotecomments: string | null }, {  }>;
    resolvefeedback: WebAttribute<Opportunity_Select, { resolvefeedback: boolean | null }, {  }>;
    salesstage: WebAttribute<Opportunity_Select, { salesstage: opportunity_salesstage | null }, { salesstage_formatted?: string }>;
    salesstagecode: WebAttribute<Opportunity_Select, { salesstagecode: opportunity_salesstagecode | null }, { salesstagecode_formatted?: string }>;
    schedulefollowup_prospect: WebAttribute<Opportunity_Select, { schedulefollowup_prospect: Date | null }, { schedulefollowup_prospect_formatted?: string }>;
    schedulefollowup_qualify: WebAttribute<Opportunity_Select, { schedulefollowup_qualify: Date | null }, { schedulefollowup_qualify_formatted?: string }>;
    scheduleproposalmeeting: WebAttribute<Opportunity_Select, { scheduleproposalmeeting: Date | null }, { scheduleproposalmeeting_formatted?: string }>;
    sendthankyounote: WebAttribute<Opportunity_Select, { sendthankyounote: boolean | null }, {  }>;
    slaid_guid: WebAttribute<Opportunity_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
    slainvokedid_guid: WebAttribute<Opportunity_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
    stageid: WebAttribute<Opportunity_Select, { stageid: string | null }, {  }>;
    statecode: WebAttribute<Opportunity_Select, { statecode: opportunity_statecode | null }, { statecode_formatted?: string }>;
    statuscode: WebAttribute<Opportunity_Select, { statuscode: opportunity_statuscode | null }, { statuscode_formatted?: string }>;
    stepid: WebAttribute<Opportunity_Select, { stepid: string | null }, {  }>;
    stepname: WebAttribute<Opportunity_Select, { stepname: string | null }, {  }>;
    timeline: WebAttribute<Opportunity_Select, { timeline: opportunity_timeline | null }, { timeline_formatted?: string }>;
    timespentbymeonemailandmeetings: WebAttribute<Opportunity_Select, { timespentbymeonemailandmeetings: string | null }, {  }>;
    timezoneruleversionnumber: WebAttribute<Opportunity_Select, { timezoneruleversionnumber: number | null }, {  }>;
    totalamount: WebAttribute<Opportunity_Select, { totalamount: number | null; transactioncurrencyid_guid: string | null }, { totalamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
    totalamount_base: WebAttribute<Opportunity_Select, { totalamount_base: number | null; transactioncurrencyid_guid: string | null }, { totalamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    totalamountlessfreight: WebAttribute<Opportunity_Select, { totalamountlessfreight: number | null; transactioncurrencyid_guid: string | null }, { totalamountlessfreight_formatted?: string; transactioncurrencyid_formatted?: string }>;
    totalamountlessfreight_base: WebAttribute<Opportunity_Select, { totalamountlessfreight_base: number | null; transactioncurrencyid_guid: string | null }, { totalamountlessfreight_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    totaldiscountamount: WebAttribute<Opportunity_Select, { totaldiscountamount: number | null; transactioncurrencyid_guid: string | null }, { totaldiscountamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
    totaldiscountamount_base: WebAttribute<Opportunity_Select, { totaldiscountamount_base: number | null; transactioncurrencyid_guid: string | null }, { totaldiscountamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    totallineitemamount: WebAttribute<Opportunity_Select, { totallineitemamount: number | null; transactioncurrencyid_guid: string | null }, { totallineitemamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
    totallineitemamount_base: WebAttribute<Opportunity_Select, { totallineitemamount_base: number | null; transactioncurrencyid_guid: string | null }, { totallineitemamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    totallineitemdiscountamount: WebAttribute<Opportunity_Select, { totallineitemdiscountamount: number | null; transactioncurrencyid_guid: string | null }, { totallineitemdiscountamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
    totallineitemdiscountamount_base: WebAttribute<Opportunity_Select, { totallineitemdiscountamount_base: number | null; transactioncurrencyid_guid: string | null }, { totallineitemdiscountamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    totaltax: WebAttribute<Opportunity_Select, { totaltax: number | null; transactioncurrencyid_guid: string | null }, { totaltax_formatted?: string; transactioncurrencyid_formatted?: string }>;
    totaltax_base: WebAttribute<Opportunity_Select, { totaltax_base: number | null; transactioncurrencyid_guid: string | null }, { totaltax_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    transactioncurrencyid_guid: WebAttribute<Opportunity_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
    traversedpath: WebAttribute<Opportunity_Select, { traversedpath: string | null }, {  }>;
    utcconversiontimezonecode: WebAttribute<Opportunity_Select, { utcconversiontimezonecode: number | null }, {  }>;
    versionnumber: WebAttribute<Opportunity_Select, { versionnumber: number | null }, {  }>;
  }
  interface Opportunity_Filter {
    accountid_guid: XQW.Guid;
    actualclosedate: Date;
    actualvalue: number;
    actualvalue_base: number;
    budgetamount: number;
    budgetamount_base: number;
    budgetstatus: budgetstatus;
    campaignid_guid: XQW.Guid;
    captureproposalfeedback: boolean;
    closeprobability: number;
    completefinalproposal: boolean;
    completeinternalreview: boolean;
    confirminterest: boolean;
    contactid_guid: XQW.Guid;
    createdby_guid: XQW.Guid;
    createdon: Date;
    createdonbehalfby_guid: XQW.Guid;
    currentsituation: string;
    customerid_guid: XQW.Guid;
    customerneed: string;
    customerpainpoints: string;
    decisionmaker: boolean;
    description: string;
    developproposal: boolean;
    discountamount: number;
    discountamount_base: number;
    discountpercentage: any;
    emailaddress: string;
    estimatedclosedate: Date;
    estimatedvalue: number;
    estimatedvalue_base: number;
    evaluatefit: boolean;
    exchangerate: any;
    filedebrief: boolean;
    finaldecisiondate: Date;
    freightamount: number;
    freightamount_base: number;
    identifycompetitors: boolean;
    identifycustomercontacts: boolean;
    identifypursuitteam: boolean;
    importsequencenumber: number;
    initialcommunication: initialcommunication;
    isprivate: boolean;
    isrevenuesystemcalculated: boolean;
    lastonholdtime: Date;
    modifiedby_guid: XQW.Guid;
    modifiedon: Date;
    modifiedonbehalfby_guid: XQW.Guid;
    name: string;
    need: need;
    onholdtime: number;
    opportunityid: XQW.Guid;
    opportunityratingcode: opportunity_opportunityratingcode;
    originatingleadid_guid: XQW.Guid;
    overriddencreatedon: Date;
    ownerid_guid: XQW.Guid;
    owningbusinessunit_guid: XQW.Guid;
    owningteam_guid: XQW.Guid;
    owninguser_guid: XQW.Guid;
    parentaccountid_guid: XQW.Guid;
    parentcontactid_guid: XQW.Guid;
    participatesinworkflow: boolean;
    presentfinalproposal: boolean;
    presentproposal: boolean;
    pricelevelid_guid: XQW.Guid;
    pricingerrorcode: qooi_pricingerrorcode;
    prioritycode: opportunity_prioritycode;
    processid: XQW.Guid;
    proposedsolution: string;
    purchaseprocess: purchaseprocess;
    purchasetimeframe: purchasetimeframe;
    pursuitdecision: boolean;
    qualificationcomments: string;
    quotecomments: string;
    resolvefeedback: boolean;
    salesstage: opportunity_salesstage;
    salesstagecode: opportunity_salesstagecode;
    schedulefollowup_prospect: Date;
    schedulefollowup_qualify: Date;
    scheduleproposalmeeting: Date;
    sendthankyounote: boolean;
    slaid_guid: XQW.Guid;
    slainvokedid_guid: XQW.Guid;
    stageid: XQW.Guid;
    statecode: opportunity_statecode;
    statuscode: opportunity_statuscode;
    stepid: XQW.Guid;
    stepname: string;
    timeline: opportunity_timeline;
    timespentbymeonemailandmeetings: string;
    timezoneruleversionnumber: number;
    totalamount: number;
    totalamount_base: number;
    totalamountlessfreight: number;
    totalamountlessfreight_base: number;
    totaldiscountamount: number;
    totaldiscountamount_base: number;
    totallineitemamount: number;
    totallineitemamount_base: number;
    totallineitemdiscountamount: number;
    totallineitemdiscountamount_base: number;
    totaltax: number;
    totaltax_base: number;
    transactioncurrencyid_guid: XQW.Guid;
    traversedpath: string;
    utcconversiontimezonecode: number;
    versionnumber: number;
  }
  interface Opportunity_Expand {
    customerid_account: WebExpand<Opportunity_Expand, Account_Select, Account_Filter, { customerid_account: Account_Result }>;
    customerid_contact: WebExpand<Opportunity_Expand, Contact_Select, Contact_Filter, { customerid_contact: Contact_Result }>;
    opportunity_PostFollows: WebExpand<Opportunity_Expand, PostFollow_Select, PostFollow_Filter, { opportunity_PostFollows: PostFollow_Result[] }>;
    opportunity_activity_parties: WebExpand<Opportunity_Expand, ActivityParty_Select, ActivityParty_Filter, { opportunity_activity_parties: ActivityParty_Result[] }>;
    opportunity_connections1: WebExpand<Opportunity_Expand, Connection_Select, Connection_Filter, { opportunity_connections1: Connection_Result[] }>;
    opportunity_connections2: WebExpand<Opportunity_Expand, Connection_Select, Connection_Filter, { opportunity_connections2: Connection_Result[] }>;
    parentaccountid: WebExpand<Opportunity_Expand, Account_Select, Account_Filter, { parentaccountid: Account_Result }>;
    parentcontactid: WebExpand<Opportunity_Expand, Contact_Select, Contact_Filter, { parentcontactid: Contact_Result }>;
  }
  interface Opportunity_FormattedResult {
    accountid_formatted?: string;
    actualclosedate_formatted?: string;
    actualvalue_base_formatted?: string;
    actualvalue_formatted?: string;
    budgetamount_base_formatted?: string;
    budgetamount_formatted?: string;
    budgetstatus_formatted?: string;
    campaignid_formatted?: string;
    contactid_formatted?: string;
    createdby_formatted?: string;
    createdon_formatted?: string;
    createdonbehalfby_formatted?: string;
    customerid_formatted?: string;
    discountamount_base_formatted?: string;
    discountamount_formatted?: string;
    estimatedclosedate_formatted?: string;
    estimatedvalue_base_formatted?: string;
    estimatedvalue_formatted?: string;
    finaldecisiondate_formatted?: string;
    freightamount_base_formatted?: string;
    freightamount_formatted?: string;
    initialcommunication_formatted?: string;
    lastonholdtime_formatted?: string;
    modifiedby_formatted?: string;
    modifiedon_formatted?: string;
    modifiedonbehalfby_formatted?: string;
    need_formatted?: string;
    opportunityratingcode_formatted?: string;
    originatingleadid_formatted?: string;
    overriddencreatedon_formatted?: string;
    ownerid_formatted?: string;
    owningbusinessunit_formatted?: string;
    owningteam_formatted?: string;
    owninguser_formatted?: string;
    parentaccountid_formatted?: string;
    parentcontactid_formatted?: string;
    pricelevelid_formatted?: string;
    pricingerrorcode_formatted?: string;
    prioritycode_formatted?: string;
    purchaseprocess_formatted?: string;
    purchasetimeframe_formatted?: string;
    salesstage_formatted?: string;
    salesstagecode_formatted?: string;
    schedulefollowup_prospect_formatted?: string;
    schedulefollowup_qualify_formatted?: string;
    scheduleproposalmeeting_formatted?: string;
    slaid_formatted?: string;
    slainvokedid_formatted?: string;
    statecode_formatted?: string;
    statuscode_formatted?: string;
    timeline_formatted?: string;
    totalamount_base_formatted?: string;
    totalamount_formatted?: string;
    totalamountlessfreight_base_formatted?: string;
    totalamountlessfreight_formatted?: string;
    totaldiscountamount_base_formatted?: string;
    totaldiscountamount_formatted?: string;
    totallineitemamount_base_formatted?: string;
    totallineitemamount_formatted?: string;
    totallineitemdiscountamount_base_formatted?: string;
    totallineitemdiscountamount_formatted?: string;
    totaltax_base_formatted?: string;
    totaltax_formatted?: string;
    transactioncurrencyid_formatted?: string;
  }
  interface Opportunity_Result extends Opportunity_Base, Opportunity_Relationships {
    "@odata.etag": string;
    accountid_guid: string | null;
    campaignid_guid: string | null;
    contactid_guid: string | null;
    createdby_guid: string | null;
    createdonbehalfby_guid: string | null;
    customerid_guid: string | null;
    modifiedby_guid: string | null;
    modifiedonbehalfby_guid: string | null;
    originatingleadid_guid: string | null;
    ownerid_guid: string | null;
    owningbusinessunit_guid: string | null;
    owningteam_guid: string | null;
    owninguser_guid: string | null;
    parentaccountid_guid: string | null;
    parentcontactid_guid: string | null;
    pricelevelid_guid: string | null;
    slaid_guid: string | null;
    slainvokedid_guid: string | null;
    transactioncurrencyid_guid: string | null;
  }
  interface Opportunity_RelatedOne {
    customerid_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
    customerid_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
    parentaccountid: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
    parentcontactid: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  }
  interface Opportunity_RelatedMany {
    opportunity_PostFollows: WebMappingRetrieve<PostFollow_Select,PostFollow_Expand,PostFollow_Filter,PostFollow_Fixed,PostFollow_Result,PostFollow_FormattedResult>;
    opportunity_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
    opportunity_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
    opportunity_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  }
}
interface WebEntitiesRetrieve {
  opportunities: WebMappingRetrieve<Dyn365WebApi.Opportunity_Select,Dyn365WebApi.Opportunity_Expand,Dyn365WebApi.Opportunity_Filter,Dyn365WebApi.Opportunity_Fixed,Dyn365WebApi.Opportunity_Result,Dyn365WebApi.Opportunity_FormattedResult>;
}
interface WebEntitiesRelated {
  opportunities: WebMappingRelated<Dyn365WebApi.Opportunity_RelatedOne,Dyn365WebApi.Opportunity_RelatedMany>;
}
interface WebEntitiesCUD {
  opportunities: WebMappingCUD<Dyn365WebApi.Opportunity_Create,Dyn365WebApi.Opportunity_Update>;
}
